import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    projects: [
      {
        test: {
          name: "node",
          environment: "node",
          include: ["src/**/*.test.ts", "e2e/scenario-catalog.test.ts"],
          exclude: [
            "src/**/*.dom.test.ts",
            "src/**/*.test.tsx",
            "src/**/*.vue.test.ts",
            "src/bindings/**/*.test.ts",
            "src/vue/**/*.test.ts",
            "src/svelte/**/*.test.ts",
            "src/angular/**/*.test.ts",
            "e2e/specs/**",
            "e2e/frameworks/**",
          ],
        },
      },
      {
        test: {
          name: "dom",
          environment: "happy-dom",
          include: [
            "src/**/*.dom.test.ts",
            "src/react/**/*.test.tsx",
          ],
        },
      },
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "json-summary", "json"],
      reportsDirectory: "coverage/core",
      all: false,
      include: [
        "src/core/sync/**/*.ts",
        "src/core/stacked/**/*.ts",
        "src/core/indicator/**/*.ts",
        "src/core/format/**/*.ts",
        "src/core/render/**/*.ts",
        "src/core/time/**/*.ts",
        "src/core/chart/NavigationUtils.ts",
        "src/core/chart/ChartScaling.ts",
        "src/core/chart/ChartAlerts.ts",
        "src/core/chart/heikinAshi.ts",
        "src/core/chart/candlestickMarkers.ts",
        "src/core/chart/positionLines.ts",
        "src/core/chart/series/SeriesActions.ts",
        "src/core/chart/exporter/**/*.ts",
        "src/core/OverlayRenderer.ts",
        "src/core/stacked/createStackedChart.ts",
        "src/core/stacked/stackExport.ts",
        "src/core/series/SeriesBounds.ts",
        "src/scales/**/*.ts",
        "src/trading/**/*.ts",
        "src/plugins/forecasting/algorithms.ts",
        "src/plugins/tools/tooltip/format.ts",
        "src/workers/downsample.ts",
        "src/workers/downsampleAsync.ts",
        "src/workers/pool.ts",
        "src/workers/indicatorsAsync.ts",
        "src/workers/indicator.worker.ts",
        "src/plugins/virtualization/index.ts",
        "src/plugins/lazy-load/index.ts",
        "src/plugins/caching/index.ts",
        "src/renderer/spike/WebGLGridSpike.ts",
        "src/plugins/drawing-tools/index.ts",
        "src/plugins/replay/index.ts",
        "src/testing/stage1BrowserBench.ts",
        "src/react/**/*.ts",
        "src/react/**/*.tsx",
      ],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
        "src/**/*.dom.test.ts",
        "src/**/*.vue.test.ts",
        "e2e/**/*.test.ts",
        "**/types.ts",
        "src/index.ts",
        "src/trading/index.ts",
      ],
    },
  },
});
